/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ashvini;

import ashvini.Course;
import ashvini.Session;
import java.awt.HeadlessException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import rakib.NewestHome;
/**
 *
 * @author ashvinipraisoody
 */
public class Lecturer extends javax.swing.JFrame {
    
    ResultSet rs = null;
    /**
     * Creates new form Lecturer
     */
    private static Statement st;
    public Lecturer() {
        initComponents();
         setSize(1940, 1020);
         setLocation(0,0);
         setResizable(false);
         st = connect.connection();
         
         if(catecombo.getSelectedItem().equals("Professor")){
            lev.setText("1");
        }
         else if(catecombo.getSelectedItem().equals("Assistant Professor")){
            lev.setText("2");
        }
         else if(catecombo.getSelectedItem().equals("Senior Lecturer(HG)")){
            lev.setText("3");
        }
         else if(catecombo.getSelectedItem().equals("Senior Lecturer")){
            lev.setText("4");
        }
         else if(catecombo.getSelectedItem().equals("Lecturer")){
            lev.setText("5");
        }
         else if(catecombo.getSelectedItem().equals("Assistant Lecturer")){
            lev.setText("6");
        }
         else if(catecombo.getSelectedItem().equals("Instructor")){
            lev.setText("7");
        }
         
         
         rank.setText(lev.getText()+'.'+id.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        nameadd = new javax.swing.JTextField();
        deptcombo = new javax.swing.JComboBox<>();
        buildcombo = new javax.swing.JComboBox<>();
        lev = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        faccombo = new javax.swing.JComboBox<>();
        centrecombo = new javax.swing.JComboBox<>();
        catecombo = new javax.swing.JComboBox<>();
        rank = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        comboselect = new javax.swing.JComboBox<>();
        textbox_search = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        search_table = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        upname = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jTextField9 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        upid = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jTextField8 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        viedetail_txt = new javax.swing.JTextArea();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        jButton12 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 51, 204));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("TIMETABLE  MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(461, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-130, 0, 1500, 70);

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESET");
        jButton3.setBorder(null);
        jButton3.setHideActionText(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(450, 370, 110, 40);

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ADD");
        jButton6.setBorder(null);
        jButton6.setHideActionText(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(570, 370, 110, 40);

        jButton4.setBackground(new java.awt.Color(0, 0, 153));
        jButton4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("UPDATE");
        jButton4.setBorder(null);
        jButton4.setHideActionText(true);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(1070, 370, 140, 40);

        jButton7.setBackground(new java.awt.Color(0, 0, 153));
        jButton7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("DELETE");
        jButton7.setBorder(null);
        jButton7.setHideActionText(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1220, 370, 140, 40);

        jButton8.setBackground(new java.awt.Color(0, 0, 153));
        jButton8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("CANCEL");
        jButton8.setBorder(null);
        jButton8.setHideActionText(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1120, 630, 120, 40);

        jButton9.setBackground(new java.awt.Color(0, 0, 153));
        jButton9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("UPDATE");
        jButton9.setBorder(null);
        jButton9.setHideActionText(true);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(1250, 630, 110, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.setBorder(null);
        jButton1.setHideActionText(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(770, 370, 140, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 153));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("VIEW");
        jButton5.setBorder(null);
        jButton5.setHideActionText(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(920, 370, 140, 40);

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.setBorder(null);
        jButton2.setHideActionText(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1110, 200, 80, 20);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Employee Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 200, 140, 17);

        jLabel17.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 204));
        jLabel17.setText("ADD EMPLOYEE");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(270, 140, 270, 20);

        nameadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameaddActionPerformed(evt);
            }
        });
        getContentPane().add(nameadd);
        nameadd.setBounds(140, 190, 190, 27);

        deptcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Computer Networking", "Information Technology" }));
        getContentPane().add(deptcombo);
        deptcombo.setBounds(490, 230, 190, 25);

        buildcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Building", "D-Block" }));
        getContentPane().add(buildcombo);
        buildcombo.setBounds(490, 270, 190, 25);

        lev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levActionPerformed(evt);
            }
        });
        getContentPane().add(lev);
        lev.setBounds(490, 310, 190, 27);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 51, 204));
        jLabel16.setText("Level");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(390, 310, 130, 17);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Building");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 270, 130, 17);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Department");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 230, 130, 17);

        faccombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Buiness", "Humanity and science" }));
        getContentPane().add(faccombo);
        faccombo.setBounds(140, 270, 190, 25);

        centrecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "Metro", "Matara", "Kandy", "Jaffna" }));
        getContentPane().add(centrecombo);
        centrecombo.setBounds(140, 230, 190, 25);

        catecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Assistant Professor", "Senior Lecturer(HG)", "Senior Lecturer", "Lecturer", "Assistant Lecturer", "Instructor" }));
        catecombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                catecomboItemStateChanged(evt);
            }
        });
        catecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catecomboActionPerformed(evt);
            }
        });
        getContentPane().add(catecombo);
        catecombo.setBounds(140, 310, 190, 25);

        rank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rankActionPerformed(evt);
            }
        });
        getContentPane().add(rank);
        rank.setBounds(140, 350, 190, 27);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Rank");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 360, 130, 17);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Category");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 320, 130, 17);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Center");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 240, 130, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Faculty");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 280, 130, 17);

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("SEARCH EMPLOYEE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(940, 140, 340, 20);

        comboselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Employee Name", "Employee ID", "Faculty", "Department", "Centre", "Level", " " }));
        comboselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboselectActionPerformed(evt);
            }
        });
        getContentPane().add(comboselect);
        comboselect.setBounds(880, 170, 230, 25);

        textbox_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_searchActionPerformed(evt);
            }
        });
        getContentPane().add(textbox_search);
        textbox_search.setBounds(880, 200, 230, 27);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("Search Employee By");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(720, 170, 170, 17);

        search_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(search_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(710, 230, 650, 130);

        jLabel15.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 204));
        jLabel15.setText("UPDATE DETAILS");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(960, 420, 340, 30);

        upname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upnameActionPerformed(evt);
            }
        });
        getContentPane().add(upname);
        upname.setBounds(830, 460, 190, 27);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 204));
        jLabel19.setText("Employee Name");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(710, 460, 140, 17);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Engineering", "Buiness", "Humanity and science" }));
        getContentPane().add(jComboBox11);
        jComboBox11.setBounds(830, 500, 190, 25);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Malabe", "Metro", "Matara", "Kandy", "Jaffna" }));
        getContentPane().add(jComboBox10);
        jComboBox10.setBounds(830, 540, 190, 25);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Professor", "Assistant Professor", "Senior Lecturer(HG)", "Senior Lecturer", "Lecturer", "Assistant Lecturer", "Instructor" }));
        jComboBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox9ItemStateChanged(evt);
            }
        });
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox9);
        jComboBox9.setBounds(830, 580, 190, 25);

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9);
        jTextField9.setBounds(830, 620, 190, 27);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 51, 204));
        jLabel23.setText("Rank");
        getContentPane().add(jLabel23);
        jLabel23.setBounds(710, 620, 130, 17);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 51, 204));
        jLabel22.setText("Category");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(710, 580, 130, 17);

        jLabel21.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 51, 204));
        jLabel21.setText("Center");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(710, 540, 130, 17);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 51, 204));
        jLabel20.setText("Faculty");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(710, 500, 130, 17);

        upid.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(upid);
        upid.setBounds(1170, 460, 190, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Software Engineering", "Computer Networking", "Information Technology" }));
        getContentPane().add(jComboBox7);
        jComboBox7.setBounds(1170, 490, 190, 25);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "New Building", "D-Block" }));
        getContentPane().add(jComboBox8);
        jComboBox8.setBounds(1170, 530, 190, 25);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(1170, 580, 190, 27);

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 51, 204));
        jLabel24.setText("Level");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(1060, 580, 130, 17);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 51, 204));
        jLabel25.setText("Building");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(1060, 540, 130, 17);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 51, 204));
        jLabel26.setText("Department");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(1060, 500, 130, 17);

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 1, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("VIEW DETAILS");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(240, 430, 300, 30);

        viedetail_txt.setColumns(20);
        viedetail_txt.setRows(5);
        jScrollPane2.setViewportView(viedetail_txt);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 460, 670, 200);

        jButton10.setBackground(new java.awt.Color(0, 0, 153));
        jButton10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("SEARCH ALL");
        jButton10.setHideActionText(true);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1210, 190, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(700, 130, 670, 290);

        jLabel28.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 51, 204));
        jLabel28.setText("Employee ID");
        getContentPane().add(jLabel28);
        jLabel28.setBounds(1060, 460, 130, 17);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(700, 420, 670, 260);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 420, 700, 260);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 204));
        jLabel8.setText("Employee ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(390, 190, 140, 17);

        id.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                idInputMethodTextChanged(evt);
            }
        });
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                idPropertyChange(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(490, 190, 190, 27);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 130, 700, 290);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setBackground(new java.awt.Color(0, 51, 204));
        label6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label6.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        label6.setForeground(new java.awt.Color(255, 255, 255));
        label6.setText("LECTURERS INFORMATION");
        getContentPane().add(label6);
        label6.setBounds(0, 70, 1370, 30);

        jButton12.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 153));
        jButton12.setText("HOME");
        jButton12.setToolTipText("");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(0, 100, 360, 30);

        jButton15.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 153));
        jButton15.setText("LECTURERS");
        jButton15.setToolTipText("");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(360, 100, 340, 30);

        jButton16.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 153));
        jButton16.setText("SUBJECTS");
        jButton16.setToolTipText("");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(700, 100, 360, 30);

        jButton17.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 153));
        jButton17.setText("SESSIONS");
        jButton17.setToolTipText("");
        jButton17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(1060, 100, 310, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameaddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameaddActionPerformed

    private void levActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_levActionPerformed

    private void rankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rankActionPerformed

    private void textbox_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_searchActionPerformed

    private void upnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upnameActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearadd();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void clearadd(){
        nameadd.setText(null);
        id.setText(null);
        lev.setText(null);
        rank.setText(null);
        faccombo.setSelectedIndex(0);
        centrecombo.setSelectedIndex(0);
        deptcombo.setSelectedIndex(0);
        buildcombo.setSelectedIndex(0);
        catecombo.setSelectedIndex(0);
    }
    
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here
        String ids=id.getText().toString();
        
        if(nameadd.getText().isEmpty() || id.getText().isEmpty() || lev.getText().isEmpty() ||rank.getText().isEmpty() )
            JOptionPane.showMessageDialog(null,"FILL ALL FIELDS");
        else if(id.getText().length() !=6){
            JOptionPane.showMessageDialog(null,"ID should be six digits");
        }
        else{
        String query = "insert into Lecturer (id,name,faculty,centre,department,category,building,level,rank) values('"+id.getText()+"','"+nameadd.getText()+"','"+faccombo.getSelectedItem()+"','"+centrecombo.getSelectedItem()+"','"+deptcombo.getSelectedItem()+"','"+buildcombo.getSelectedItem()+"','"+catecombo.getSelectedItem()+"','"+lev.getText()+"','"+rank.getText()+"')";
        try {
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"EMPLOYEE ADDED SUCCESSFULLY");
            clearadd();
        } catch (SQLException ex) {
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         if(!search_table.getSelectionModel().isSelectionEmpty()){
        int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
        upid.setText(model.getValueAt(i, 0).toString());
        jComboBox11.addItem(model.getValueAt(i, 2).toString());
        jComboBox10.addItem(model.getValueAt(i, 3).toString());
        upname.setText(model.getValueAt(i, 1).toString());
        jTextField8.setText(model.getValueAt(i, 7).toString());
        jTextField9.setText(model.getValueAt(i, 8).toString());
        jComboBox7.addItem(model.getValueAt(i, 4).toString());
        jComboBox8.addItem(model.getValueAt(i, 5).toString());
        jComboBox9.addItem(model.getValueAt(i, 6).toString());
        viedetail_txt.setText(null);
       // jDateChooser4.setDate(convertUtilDateToSqlDate(model.getValueAt(i, 5)); 
         }
         else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO UPDATE");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void clearupdate(){
        upname.setText(null);
        upid.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jComboBox11.setSelectedIndex(0);
        jComboBox10.setSelectedIndex(0);
        jComboBox7.setSelectedIndex(0);
        jComboBox8.setSelectedIndex(0);
        jComboBox9.setSelectedIndex(0);
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
               if(!search_table.getSelectionModel().isSelectionEmpty()){
        // TODO add your handling code here:
       int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO DELETE?", "DELETE", JOptionPane.YES_NO_OPTION);
        if(op==0){
        try{
            int i = search_table.getSelectedRow();
            TableModel model = search_table.getModel();
            
            String sql2 = "DELETE FROM Lecturer WHERE id = '"+model.getValueAt(i, 0).toString()+"'";
            st.executeUpdate(sql2);
            JOptionPane.showMessageDialog(null, "DELETED SUCCESSFULLY");
            
            DefaultTableModel model1= (DefaultTableModel) search_table.getModel();
            model1.setRowCount(0);
            viedetail_txt.setText(null);
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        }
         }
        else
              JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO DELETE");
        
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        clearupdate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         if(upname.getText().isEmpty() || upid.getText().isEmpty() || jTextField8.getText().isEmpty() ||jTextField9.getText().isEmpty() )
            JOptionPane.showMessageDialog(null,"FILL ALL FIELDS TO UPDATE");
        else{
            int op = JOptionPane.showConfirmDialog(null, "ARE YOU SURE YOU WANT TO UPDATE THIS RECORD?", "UPDATE", JOptionPane.YES_NO_OPTION);
            if(op==0){ 
                 String query = "UPDATE Lecturer SET name='"+upname.getText()+"', faculty= '"+jComboBox11.getSelectedItem()+"', centre='"+jComboBox10.getSelectedItem()+"', department= '"+jComboBox7.getSelectedItem()+"',category= '"+jComboBox9.getSelectedItem()+"',building= '"+jComboBox8.getSelectedItem()+"',level= '"+jTextField8.getText()+"',rank= '"+jTextField9.getText()+"' WHERE id= '"+upid.getText()+"'";
                try {
                    st.executeUpdate(query);
                    JOptionPane.showMessageDialog(null,"EMPLOYEE UPDATED SUCCESSFULLY");
                    clearupdate();
                    DefaultTableModel model = (DefaultTableModel) search_table.getModel();
                    model.setRowCount(0);
            
                } catch (SQLException ex) {
                     Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) search_table.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if(!search_table.getSelectionModel().isSelectionEmpty()){
        // TODO add your handling code here:
        try{
        int i = search_table.getSelectedRow();
        TableModel model = search_table.getModel();
        
        viedetail_txt.setText("*******************************************EMPLOYEE DETAILS***************************************\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Employee ID : " + model.getValueAt(i, 0).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Employee Name : " + model.getValueAt(i, 1).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Faculty : " + model.getValueAt(i, 2).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Center : " + model.getValueAt(i, 3).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Department : " + model.getValueAt(i, 4).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Category : "  + model.getValueAt(i, 6).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Building : " + model.getValueAt(i, 5).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Level : " + model.getValueAt(i, 7).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+"Rank : " + model.getValueAt(i, 8).toString()+"\n");
        }catch(Exception ex){
            
        }
        }
        else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO VIEW");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if(!textbox_search.getText().isEmpty()){
                Object sel1 = comboselect.getSelectedItem();
                String selitem = sel1.toString();
            
            if("Employee ID".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE id = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Id you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
                finally{
                try{
                     rs.close();
            }
            catch(Exception e){
                
            }
        }
            }
            else if("Employee Name".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE name = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Name you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
            else if("Faculty".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE faculty = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Faculty you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
          else if("Department".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE department = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Department you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
            else if("Centre".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE centre = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Center you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
            else if("Level".equals(selitem)){
                try{
                    String sql2 = "SELECT * FROM Lecturer WHERE level = '"+textbox_search.getText()+"'";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                        if(search_table.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"No employee in this level");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
         }
         else
             JOptionPane.showMessageDialog(null,"PLEASE SPECIFY WHAT YOU NEED TO SEARCH");
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
        rank.setText(lev.getText()+'.'+id.getText());
    }//GEN-LAST:event_idActionPerformed

    private void catecomboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_catecomboItemStateChanged
        // TODO add your handling code here:
        if(catecombo.getSelectedItem().equals("Professor")){
            lev.setText("1");
        }
         else if(catecombo.getSelectedItem().equals("Assistant Professor")){
            lev.setText("2");
        }
         else if(catecombo.getSelectedItem().equals("Senior Lecturer(HG)")){
            lev.setText("3");
        }
         else if(catecombo.getSelectedItem().equals("Senior Lecturer")){
            lev.setText("4");
        }
         else if(catecombo.getSelectedItem().equals("Lecturer")){
            lev.setText("5");
        }
         else if(catecombo.getSelectedItem().equals("Assistant Lecturer")){
            lev.setText("6");
        }
         else if(catecombo.getSelectedItem().equals("Instructor")){
            lev.setText("7");
        }
        
        rank.setText(lev.getText()+'.'+id.getText());
    }//GEN-LAST:event_catecomboItemStateChanged

    private void idInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_idInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputMethodTextChanged

    private void idPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_idPropertyChange
        // TODO add your handling code here:
        rank.setText(lev.getText()+'.'+id.getText());
    }//GEN-LAST:event_idPropertyChange

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        // TODO add your handling code here:
        rank.setText(lev.getText()+'.'+id.getText());
    }//GEN-LAST:event_idKeyTyped

    private void comboselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboselectActionPerformed

    private void catecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catecomboActionPerformed

    private void jComboBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox9ItemStateChanged
        // TODO add your handling code here:
          if(jComboBox9.getSelectedItem().equals("Professor")){
            jTextField8.setText("1");
        }
         else if(jComboBox9.getSelectedItem().equals("Assistant Professor")){
            jTextField8.setText("2");
        }
         else if(jComboBox9.getSelectedItem().equals("Senior Lecturer(HG)")){
            jTextField8.setText("3");
        }
         else if(jComboBox9.getSelectedItem().equals("Senior Lecturer")){
            jTextField8.setText("4");
        }
         else if(jComboBox9.getSelectedItem().equals("Lecturer")){
            jTextField8.setText("5");
        }
         else if(jComboBox9.getSelectedItem().equals("Assistant Lecturer")){
            jTextField8.setText("6");
        }
         else if(jComboBox9.getSelectedItem().equals("Instructor")){
            jTextField8.setText("7");
        }
        
        jTextField9.setText(jTextField8.getText()+'.'+upid.getText());
    }//GEN-LAST:event_jComboBox9ItemStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         try{
                    String sql2 = "SELECT * FROM Lecturer";
                    rs = st.executeQuery(sql2);
                    search_table.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO SESSION PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Session l1 = new Session();
            l1.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO SUBJECTS PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Course l1 = new Course();
            l1.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, "YOU ARE ALREADY IN LECTURERS PAGE. DO YOU WANT TO RESET THE PAGE?", "PAGE RESET", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Lecturer co = new Lecturer();
            co.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "HOME PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            NewestHome h = new NewestHome();
            h.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lecturer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lecturer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buildcombo;
    private javax.swing.JComboBox<String> catecombo;
    private javax.swing.JComboBox<String> centrecombo;
    private javax.swing.JComboBox<String> comboselect;
    private javax.swing.JComboBox<String> deptcombo;
    private javax.swing.JComboBox<String> faccombo;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Label label3;
    private java.awt.Label label6;
    private javax.swing.JTextField lev;
    private javax.swing.JTextField nameadd;
    private javax.swing.JTextField rank;
    private javax.swing.JTable search_table;
    private javax.swing.JTextField textbox_search;
    private javax.swing.JLabel upid;
    private javax.swing.JTextField upname;
    private javax.swing.JTextArea viedetail_txt;
    // End of variables declaration//GEN-END:variables
}
