/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ashvini;

import ashvini.Course;
import ashvini.Lecturer;
import java.awt.Button;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import rakib.NewestHome;

/**
 *
 * @author ashvinipraisoody
 */
public class Session extends javax.swing.JFrame {

    /**
     * Creates new form Session
     */
    private static Statement st;
    ResultSet rs = null;
    ArrayList<String> choice = new ArrayList<>();
    String cod;
    int i = 0;
    public Session() {
        initComponents();
        setSize(1940, 1020);
         setLocation(0,0);
         setResizable(false);
         st = connect.connection();
         loadlecturer();
         loadtags();
         loadsubject();
         DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
         model.setRowCount(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label3 = new java.awt.Label();
        jLabel20 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        textbox_search = new javax.swing.JTextField();
        comboselect = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viedetail_txt = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        jButton10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        spin1 = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(0, 51, 204));
        label3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label3.setFont(new java.awt.Font("Baskerville Old Face", 1, 60)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("TIMETABLE  MANAGEMENT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(447, 447, 447)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(758, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-130, 0, 2040, 70);

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 204));
        jLabel20.setText("ADD SESSION");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(270, 140, 220, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        jComboBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox4ItemStateChanged(evt);
            }
        });
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(480, 210, 200, 25);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(480, 290, 200, 27);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 204));
        jLabel12.setText("Student count");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(380, 300, 120, 17);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("ID HERE");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 180, 200, 17);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 51, 204));
        jLabel15.setText("Session ID");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(380, 180, 120, 17);

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("ADD");
        jButton6.setBorder(null);
        jButton6.setHideActionText(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(540, 350, 130, 40);

        jButton3.setBackground(new java.awt.Color(0, 0, 153));
        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("RESET");
        jButton3.setBorder(null);
        jButton3.setHideActionText(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(390, 350, 130, 40);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        jComboBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox5ItemStateChanged(evt);
            }
        });
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(480, 250, 200, 30);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(200, 170, 170, 25);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("Lecturer Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 170, 130, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 204));
        jLabel9.setText("Subject");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(380, 260, 120, 20);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 204));
        jLabel11.setText("Group/ Subgroup ID");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 300, 170, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 204));
        jLabel13.setText("Duration (Hours)");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 340, 140, 17);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.setBorder(null);
        jButton1.setHideActionText(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1090, 360, 120, 40);

        jButton5.setBackground(new java.awt.Color(0, 0, 153));
        jButton5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("VIEW");
        jButton5.setBorder(null);
        jButton5.setHideActionText(true);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1230, 360, 120, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(700, 230, 650, 120);

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("SEARCH");
        jButton2.setBorder(null);
        jButton2.setHideActionText(true);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1100, 200, 80, 20);

        textbox_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_searchActionPerformed(evt);
            }
        });
        getContentPane().add(textbox_search);
        textbox_search.setBounds(860, 200, 230, 27);

        comboselect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Subject", "Group ID" }));
        comboselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboselectActionPerformed(evt);
            }
        });
        getContentPane().add(comboselect);
        comboselect.setBounds(860, 170, 130, 25);

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 204));
        jLabel18.setText("SEARCH SESSION");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(930, 140, 390, 20);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 204));
        jLabel14.setText("Search Session By");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(710, 170, 160, 17);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Lecturers"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 200, 360, 100);

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 204));
        jLabel19.setText("VIEW SESSION");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(600, 420, 390, 20);

        viedetail_txt.setColumns(20);
        viedetail_txt.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        viedetail_txt.setRows(5);
        jScrollPane1.setViewportView(viedetail_txt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 450, 1320, 200);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 204));
        jLabel10.setText("Tags");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 220, 120, 17);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 410, 1370, 260);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(690, 410, 680, 260);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel4.setText("jLabel1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 410, 690, 260);

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setBackground(new java.awt.Color(0, 51, 204));
        label5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label5.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setText("SESSION INFORMATION");
        getContentPane().add(label5);
        label5.setBounds(-230, 70, 1910, 30);

        jButton10.setBackground(new java.awt.Color(0, 0, 153));
        jButton10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("SEARCH ALL");
        jButton10.setHideActionText(true);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(1200, 190, 150, 30);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 130, 680, 280);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(200, 300, 170, 30);
        getContentPane().add(spin1);
        spin1.setBounds(200, 340, 170, 28);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ashvini/background.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(0, 51, 204), new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 204)));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 690, 280);

        jButton17.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 0, 153));
        jButton17.setText("SESSIONS");
        jButton17.setToolTipText("");
        jButton17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17);
        jButton17.setBounds(1060, 100, 310, 30);

        jButton16.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 0, 153));
        jButton16.setText("SUBJECTS");
        jButton16.setToolTipText("");
        jButton16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16);
        jButton16.setBounds(690, 100, 370, 30);

        jButton15.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 0, 153));
        jButton15.setText("LECTURERS");
        jButton15.setToolTipText("");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15);
        jButton15.setBounds(330, 100, 360, 30);

        jButton12.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 0, 153));
        jButton12.setText("HOME");
        jButton12.setToolTipText("");
        jButton12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 153), new java.awt.Color(0, 51, 204), new java.awt.Color(0, 0, 255), new java.awt.Color(51, 0, 204)));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12);
        jButton12.setBounds(0, 100, 330, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadlecturer(){
        String sql = "SELECT * FROM Lecturer";
        try{
            st.executeUpdate(sql);
            rs = st.executeQuery(sql);
            while(rs.next()){
                jComboBox3.addItem(rs.getString("name"));
            }
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void loadtags(){
        String sql1 = "SELECT * FROM tags";
        try{
            st.executeUpdate(sql1);
            rs = st.executeQuery(sql1);
            while(rs.next()){
                jComboBox4.addItem(rs.getString("Tags"));
            }
            
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
        private void loadsubject(){
        String sql2 = "SELECT * FROM Course";
        try{
            st.executeUpdate(sql2);
            rs = st.executeQuery(sql2);
            while(rs.next()){
                jComboBox5.addItem(rs.getString("name"));
            }
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }
        
        private void loadgroup(){
        String sql2 = "SELECT * FROM GroupIdGen";
        try{
            st.executeUpdate(sql2);
            rs = st.executeQuery(sql2);
            while(rs.next()){
                jComboBox2.addItem(rs.getString("GroupID"));
            }
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }
       
        
        private void loadsubgroup(){
        String sql2 = "SELECT * FROM subGroupIdGen";
        try{
            st.executeUpdate(sql2);
            rs = st.executeQuery(sql2);
            while(rs.next()){
                jComboBox2.addItem(rs.getString("SubGroupId"));
            }
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }
    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        
        for(int i = 0; i<model1.getRowCount();i++){
                if(model1.getValueAt(i, 0).toString().equals(jLabel8.getText().toString())){
                    JOptionPane.showMessageDialog(null,"SESSION ALREADY ADDED");
                }
        }
        
       if(jTextField2.getText().isEmpty())
           JOptionPane.showMessageDialog(null,"FILL ALL FIELDS");
       else{
        String query = "insert into Sessions(Id,tag,subject,groupid,count,duration,subcod) values('"+jLabel8.getText()+"','"+jComboBox4.getSelectedItem()+"','"+jComboBox5.getSelectedItem()+"','"+jComboBox2.getSelectedItem()+"','"+jTextField2.getText()+"','"+spin1.getValue().toString()+"','"+cod+"')";
        try {
            st.executeUpdate(query);
            TableModel model = jTable2.getModel();
          for(i=0;i<model.getRowCount();i++){
                String sq = "insert into SessionLecturers (id,lecturer) values('"+jLabel8.getText()+"','"+model.getValueAt(i,0).toString()+"')";
                try{
                    st.executeUpdate(sq);
                }catch (SQLException ex) {
                    Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
                }
           }
            JOptionPane.showMessageDialog(null,"Session ADDED SUCCESSFULLY");
            Session l1 = new Session();
            l1.setVisible(true);
            this.setVisible(false);
       } catch (Exception ex) {
           Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, ex);
       }
        }
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        clearadd();
    }//GEN-LAST:event_jButton3ActionPerformed

      private void clearadd(){
       jTextField2.setText(null);
        spin1.setValue(0);
        jComboBox3.setSelectedIndex(0);
        jComboBox4.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        jComboBox2.removeAllItems();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        jLabel8.setText(null);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        viedetail_txt.setText(null);
        if(!jTable1.getSelectionModel().isSelectionEmpty()){
        // TODO add your handling code here:
        try{
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        
        viedetail_txt.setText("______________________________________________"+viedetail_txt.getText()+model.getValueAt(i, 0).toString()+"______________________________________________\n\n");
        viedetail_txt.setText(viedetail_txt.getText()+model.getValueAt(i, 7).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+model.getValueAt(i, 2).toString()+"("+model.getValueAt(i, 3).toString()+")"+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+model.getValueAt(i, 1).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+model.getValueAt(i, 4).toString()+"\n");
        viedetail_txt.setText(viedetail_txt.getText()+model.getValueAt(i, 5).toString()+"("+model.getValueAt(i, 6).toString()+")"+"\n");
        }catch(Exception ex){
            
        }
        }
        else
             JOptionPane.showMessageDialog(null, "NOTHING SPECIFIED TO VIEW");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!textbox_search.getText().isEmpty()){
                Object sel1 = comboselect.getSelectedItem();
                String selitem = sel1.toString();
                
                if("Lecturer".equals(selitem)){
                try{
                    String sql2 = "SELECT s.Id,s.tag,s.subject,s.subcod,s.groupid,s.count,s.duration,group_concat(l.lecturer)AS Lecturers  FROM Sessions s INNER JOIN SessionLecturers l ON S.Id=l.id WHERE l.lecturer = '"+textbox_search.getText()+"' GROUP BY s.Id";
            rs = st.executeQuery(sql2);
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        if(jTable1.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Lecturer name you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
                else if("Subject".equals(selitem)){
                try{
                    String sql2 = "SELECT s.Id,s.tag,s.subject,s.subcod,s.groupid,s.count,s.duration,group_concat(l.lecturer)AS Lecturers  FROM Sessions s INNER JOIN SessionLecturers l ON S.Id=l.id WHERE s.subject = '"+textbox_search.getText()+"' GROUP BY s.Id";
            rs = st.executeQuery(sql2);
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        if(jTable1.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Subject name you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
                 else if("Group ID".equals(selitem)){
                try{
                    String sql2 = "SELECT s.Id,s.tag,s.subject,s.subcod,s.groupid,s.count,s.duration,group_concat(l.lecturer)AS Lecturers  FROM Sessions s INNER JOIN SessionLecturers l ON S.Id=l.id WHERE s.groupid = '"+textbox_search.getText()+"' GROUP BY s.Id";
            rs = st.executeQuery(sql2);
                    jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                        if(jTable1.getModel().getRowCount()<=0)
                            JOptionPane.showMessageDialog(null,"The Group ID you have entered is NOT available");
                    }
                 catch(HeadlessException | SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                 }
            }
         }
         else
             JOptionPane.showMessageDialog(null,"PLEASE SPECIFY WHAT YOU NEED TO SEARCH");        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textbox_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textbox_searchActionPerformed

    private void comboselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboselectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboselectActionPerformed

    private void jComboBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox4ItemStateChanged
        // TODO add your handling code here:
        if(jComboBox4.getSelectedItem().toString().equals("LECTURE") || jComboBox4.getSelectedItem().toString().equals("TUTORIAL")){
                jComboBox2.removeAllItems();
                loadgroup();
            }
            else if(jComboBox4.getSelectedItem().toString().equals("LAB")){
                jComboBox2.removeAllItems();
                loadsubgroup();
            }
       
    }//GEN-LAST:event_jComboBox4ItemStateChanged

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
        
    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
        // TODO add your handling code here:
        String item = jComboBox3.getSelectedItem().toString();
        
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        
        for(int i = 0; i<choice.size();i++){
                if(choice.get(i).toString().equals(item)){
                    JOptionPane.showMessageDialog(null,"LECTURER ALREADY ADDED");
                    model.removeRow(model.getRowCount());
                }
        }
        choice.add(item);
        
        model.setRowCount(0);
       
        for(int i = 0; i<choice.size();i++){
                Object[] row = {choice.get(i)};
                model.addRow(row);
        }
        
        int r = model.getRowCount();
        model.removeRow(r);
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox5ItemStateChanged
        // TODO add your handling code here:
        jLabel8.setText(jComboBox2.getSelectedItem().toString() + '_' + jComboBox5.getSelectedItem().toString() + '_' + jComboBox4.getSelectedItem().toString());
        
         String sql2 = "SELECT * FROM Course WHERE name = '"+jComboBox5.getSelectedItem()+"'";
        try{
            st.executeUpdate(sql2);
            rs = st.executeQuery(sql2);
            cod = rs.getString("code");
        }catch(Exception e){
            Logger.getLogger(Lecturer.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_jComboBox5ItemStateChanged

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        try{
            String sql2 = "SELECT s.Id,s.tag,s.subject,s.subcod,s.groupid,s.count,s.duration,group_concat(l.lecturer)AS Lecturers  FROM Sessions s INNER JOIN SessionLecturers l ON S.Id=l.id GROUP BY s.Id";
            rs = st.executeQuery(sql2);
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(HeadlessException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null,"YOU ARE ALREADY IN SESSION PAGE. DO YOU WANT TO RESET PAGE?", "RESET SESSION PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Session l1 = new Session();
            l1.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "CHANGE TO SUBJECTS PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Course l1 = new Course();
            l1.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null, " ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "LECTURER PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            Lecturer co = new Lecturer();
            co.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        int op = JOptionPane.showConfirmDialog(null," ARE YOU SURE YOU WANT TO LEAVE THIS PAGE?", "HOME PAGE", JOptionPane.YES_NO_OPTION);
        if(op==0){
            NewestHome h = new NewestHome();
            h.setVisible(true);
            this.setVisible(false);}
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Session.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Session().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboselect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label label3;
    private java.awt.Label label5;
    private javax.swing.JSpinner spin1;
    private javax.swing.JTextField textbox_search;
    private javax.swing.JTextArea viedetail_txt;
    // End of variables declaration//GEN-END:variables
}
